name: Kalkulator CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Ustaw Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Instaluj zależności
        run: |
          pip install -r requirements.txt

      - name: Uruchom testy
        run: pytest
